from . import policy_keys
from . import egress_keys
from . import upa_catalog
from . import operation_type
from . import preception_deduction
from . import res_partner
from . import calendar_payment_reg
from . import employee_payroll
from . import payment_request
from . import upa_document_type
from . import payroll_payment_invoice
from . import account_journal